name = "attendly"
pages_build_output_dir = ".vercel/output/static"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat_v2"]

[vars]
NEXT_PUBLIC_SUPABASE_URL = "https://yuzygpommgawbmdrzsxn.supabase.co"
NEXT_PUBLIC_SUPABASE_ANON_KEY = "sb_publishable_Z9peJ2CystiLxoLAa5dpLw_bwD90etn"
NEXT_PUBLIC_WORKERS_URL = "https://attendly-workers.won03289.workers.dev"
